load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_handtracking",
    calculators = ["//mediapipe/graphs/hand_tracking:mobile_calculators"],
)

